Global:
  output_dir: "./resources"
  provider_format: 'openai' # can only be ['openai', 'mlx_lm']
  provider: "lmstudio" # can only be ['openai', 'lmstudio', 'ollama', 'groq', 'other']
  base_url: '' # Only needed to be filled if provider is 'other'
  api_key: '' # Only needed to be filled if provider is 'other', or 'openai', and 'groq'

Step1:
  model_name: "mlx-community/Josiefied-Qwen2.5-1.5B-Instruct-abliterated-v1-4bit"
  max_tokens: 512
  temperature: 0.7
  chunk_size: 1000
  max_chars: 100000

Step2:
  model_name: "mlx-community/Josiefied-Qwen2.5-14B-Instruct-abliterated-v4-4-bit"
  max_tokens: 8126
  temperature: 1
  length: "long" # can only be ["short", "medium", "long", "very-long"]
  style: "academic" # can only be ["friendly", "professional", "academic", "casual", "technical", "funny"]

Step3:
  model_name: "mlx-community/Josiefied-Qwen2.5-14B-Instruct-abliterated-v4-4-bit"
  max_tokens: 8126
  temperature: 1

Step4:
  model_name: "lucasnewman/f5-tts-mlx"
  cohost_speaker_ref_audio_path: "./voices/cohost.wav"
  cohost_speaker_ref_audio_text: "Some call me nature, others call me mother nature."