Global:
  output_dir: "./resources"
  provider_format: 'openai' # can only be ['openai', 'mlx_lm']
  provider: "lmstudio" # can only be ['openai', 'lmstudio', 'ollama', 'groq', 'other']
  base_url: ''
  api_key: ''

Step1:
  model_name: "mlx-community/Josiefied-Qwen2.5-1.5B-Instruct-abliterated-v1-4bit"
  max_tokens: 512
  temperature: 0.7
  chunk_size: 1000
  max_chars: 100000